"""Shell integration — generate wrapper scripts and aliases for auto-inject."""

from __future__ import annotations

import os
import platform
from pathlib import Path

from .core import MemoryEngine
from .recall import build_context_brief

SHELL_ALIASES = {
    "bash": """
# AgentMemory shell integration
# Add this to your ~/.bashrc

# Auto-load context before starting Claude Code
claude() {
    local project_dir="${1:-.}"
    local project_name=$(cd "$project_dir" && python -c \
        "from agentmemory.cli import _get_project; print(_get_project())" \
        2>/dev/null || basename "$PWD")  # noqa: E501
    echo "Loading AgentMemory context for $project_name..."
    agentmemory load --project "$project_name" 2>/dev/null || true
    command claude "$@"
}

# Quick capture aliases
amc() { agentmemory capture "$@"; }
amr() { agentmemory recall "$@"; }
ams() { agentmemory search "$@"; }
aml() { agentmemory load "$@"; }
""",
    "zsh": """
# AgentMemory shell integration
# Add this to your ~/.zshrc

# Auto-load context before starting Claude Code
claude() {
    local project_dir="${1:-.}"
    local project_name=$(cd "$project_dir" && python -c "from agentmemory.cli import _get_project; print(_get_project())" 2>/dev/null || basename "$PWD")
    echo "Loading AgentMemory context for $project_name..."
    agentmemory load --project "$project_name" 2>/dev/null || true
    command claude "$@"
}

# Quick capture aliases
alias amc='agentmemory capture'
alias amr='agentmemory recall'
alias ams='agentmemory search'
alias aml='agentmemory load'
""",
    "powershell": """
# AgentMemory shell integration
# Add this to your $PROFILE

# Auto-load context before starting Claude Code
function claude {
    param([string]$ProjectDir = ".")
    $cwd = (Resolve-Path $ProjectDir).Path
    $projectName = python -c \
        "from agentmemory.cli import _get_project; print(_get_project())" 2>$null
    if (-not $projectName) { $projectName = Split-Path $cwd -Leaf }
    Write-Host "Loading AgentMemory context for $projectName..."
    agentmemory load --project $projectName 2>$null | Out-Null
    & claude @args
}

# Quick capture aliases
function amc { agentmemory capture @args }
function amr { agentmemory recall @args }
function ams { agentmemory search @args }
function aml { agentmemory load @args }
""",
    "fish": """
# AgentMemory shell integration
# Add this to your ~/.config/fish/config.fish

# Auto-load context before starting Claude Code
function claude
    set project_dir (test -n "$argv[1]"; and echo $argv[1]; or echo ".")
    set project_name (python -c \
        "from agentmemory.cli import _get_project; print(_get_project())" \
        2>/dev/null; or basename $PWD)
    echo "Loading AgentMemory context for $project_name..."
    agentmemory load --project $project_name 2>/dev/null
    command claude $argv
end

# Quick capture aliases
alias amc='agentmemory capture'
alias amr='agentmemory recall'
alias ams='agentmemory search'
alias aml='agentmemory load'
""",
}


def detect_shell() -> str:
    """Detect the current shell."""
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    if "bash" in shell:
        return "bash"
    if "fish" in shell:
        return "fish"
    if platform.system() == "Windows":
        return "powershell"
    return "bash"


def generate_shell_integration(shell: str | None = None) -> str:
    """Generate shell integration script for the given shell."""
    shell = shell or detect_shell()
    if shell not in SHELL_ALIASES:
        shell = "bash"
    return SHELL_ALIASES[shell]


def install_shell_integration(shell: str | None = None) -> Path:
    """Install shell integration by printing instructions."""
    shell = shell or detect_shell()
    script = generate_shell_integration(shell)
    config_file = _get_shell_config_path(shell)
    return config_file, script


def _get_shell_config_path(shell: str) -> Path:
    """Get the config file path for a shell."""
    home = Path.home()
    paths = {
        "bash": home / ".bashrc",
        "zsh": home / ".zshrc",
        "fish": home / ".config" / "fish" / "config.fish",
        "powershell": home / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1",
    }
    return paths.get(shell, home / ".bashrc")


def create_wrapper_script(project: str, output: Path | None = None) -> Path:
    """Create a wrapper script that loads memory before opening an agent.

    Usage: ./claude-with-memory -> loads context, then runs claude
    """
    engine = MemoryEngine()
    brief = build_context_brief(engine, project)

    script_content = f"""#!/usr/bin/env bash
# Auto-generated by AgentMemory — loads context before starting Claude Code

PROJECT="{project}"
echo "Loading AgentMemory context for $PROJECT..."

# Export context as environment variable for Claude to read
export AGENT_MEMORY_CONTEXT=$(cat <<'EOF'
{brief}
EOF
)

# Start Claude with context pre-loaded
claude "$@"
"""
    if output is None:
        output = Path.cwd() / f"claude-memory-{project}"
    output.write_text(script_content, encoding="utf-8")
    os.chmod(output, os.stat(output).st_mode | 0o111)
    return output
